feat: make documentation directory configurable
deven-org/documentation-skeleton pull request #55
Opened 2024-02-13 15:03 UTC by kathikraemer

2024-02-15 08:29 UTC, Jumace requested changes

2024-02-16 12:48 UTC, Jumace requested changes
Great work, only one least thing I forgot to mention last time:
Please execute the `self:update` so that the config file is updated with the directory.

2024-02-19 06:59 UTC, kathikraemer commented
> Great work, only one least thing I forgot to mention last time: Please execute the `self:update` so that the config file is updated with the directory.

I thought it would be better to wait for the next release until we update so that the version number is also correct.

2024-02-19 07:23 UTC, Jumace approved these changes

2024-02-19 07:39 UTC, merged